### ISSUE TITLE
Update Parser

### ISSUE THREAD

**Issue by RobLoach** [RobLoach/node-raylib#145]
[raylib_api.json](https://github.com/raysan5/raylib/blob/master/parser/raylib_api.json) now includes...
- Aliases
- `FLOAT_MATH` instead of `UNKNOWN`
- Actual Matrix

**Comment by twuky** [comment]
Those new things will need to be looked into for sure.

At the current moment - this new raylib_api.json file is *not* consisent with raylib 4.0's API - its more indicative of raylib 4.1 really, which isn't a currently tagged release for raylib. Some function names and parameter types have been changed since 4.0 released.

Right now Cmake-JS pulls down the 4.0 git tagged raylib, so we also need to use the JSON file associated with that or we can't build properly. Currently the parser [grabs a specific version](https://github.com/RobLoach/node-raylib/blob/46e87ae7bf2d98974ec9acb5955ddb9ba3cfa2b1/tools/generate.js#L98) of the api to ensure compatibility with what cmake uses.

So I think currently we only need to update the parser if either a new release / git tag of raylib comes out.

We could try working on writing things so they are always in sync with the main raylib github branch. but because of the generator / build system that would mean the API of the npm package would not be deterministic based on version any more?

**Comment by twuky** [comment]
Possibly a better way to go about this is to simply include the version of the JSON in this repo, but I wasn't sure how that would act with raylib's license, so at the moment it pulls it with fetch().

**Comment by konsumer** [comment]
I added the download of the json, just because I don't like including derived, referenced, or built things as copies, in git. I like it when everything can be tracked back to it's file-history, issue-queue, CI action, etc, so personally I am a bit opposed to including the json file, if it doesn't simplify things or have any other benefits.

[It uses a specific commit-hash](https://github.com/RobLoach/node-raylib/blob/master/tools/generate.js#L98) to lock it into a specific version, so I think we can pair the JSON api/node-raylib fine by just updating the hash to be whatever the script can build for. If we want to support 4.1 in generator, we can just update the hash & generator code, all in 1 go.

**Comment by twuky** [comment]
The only issue with it as it is now is that it can be a bit cumbersome to actually find the right commit to use. the JSON file is not updated automatically in raylib's repo - so it only gets updated when someone manually runs the tool and decides to commit the result.

Maybe we can get our CI system to self-publish the JSON file and uploaded to releases like it does our native addon files. Then node-raylib doesn't have to pull anything from an "uncontrolled" environment when parsing/generating?

**Comment by konsumer** [comment]
> The only issue with it as it is now is that it can be a bit cumbersome to actually find the right commit to use. the JSON file is not updated automatically in raylib's repo - so it only gets updated when someone manually runs the tool and decides to commit the result.

Yeh, and they don't seem to tag until it's finished, and generate when they are doing a release, which makes sense, but is maybe an argument to work on this as a future-thing (to anticpate the chnages before 4.1 is released) but not tag for current release of node-raylib.

If you don't tag, it doesn't release, so it could just be a branch of code that floats around until 4.1 gets released.

**Comment by RobLoach** [comment]
Built it manually against 4.0.0 over at https://gist.github.com/RobLoach/61477c6ff34764e1c3962031d4dd3f8c ... K.I.S.S :wink:
