### ISSUE TITLE
Quick start instructions don't work for Mac M1

### ISSUE THREAD

**Issue by davjhan** [RobLoach/node-raylib#169]
Hi! I'm trying to get the README instructions to run on my M1 macbook, but I'm getting the following error:

```
error: Cannot find module "../../build/Release/node-raylib.node" from "/Users/{my projects path}/raylib-hello-world/node_modules/raylib/src/generated/node-raylib.js"

```
And in [Releases](https://github.com/RobLoach/node-raylib/releases), I don't see a fitting build for M1 macs. In fact, when I run 
`node node_modules/raylib/tools/generate.js`, I see:

```
Checking for https://github.com/RobLoach/node-raylib/releases/download/vundefined/node-raylib-darwin-arm64.node
Status: 404
Not found. Building.
```

According to [this other issue](https://github.com/RobLoach/node-raylib/issues/95), it should 'just work' for Mac M1. Are there further instructions that I have to follow to get this running?

Thanks.

**Comment by davjhan** [comment]
@konsumer

**Comment by davjhan** [comment]
NVM! Sorry, this must have been because I was using `bun` to install. But cleaning my node_modules and reinstalling it via `npm install` worked as expected.

**Comment by twuky** [comment]
M1 is the only platform we don't have CI able to build automatically right now. there were a few versions where @konsumer built it and uploaded manually to the Releases, but we don't have it for 4.5 yet.

also for the bun runtime- its been a while since I tested but even if you got it installed I remember bun having some issues. It seemed to treat floating points wrong or something to that effect, and I couldn't render anything. If that's working now I'd be interested to hear how it performs!

**Comment by konsumer** [comment]
I can compile a ready-made for M1, but also if you have build tools (c compiler and `cmake`) you should also be able to automatically compile when you `npm i`.

Basically, we add those as a convenience, so users don't have to recompile the native module, but "normal" use would be that it compiles the source for the current platform.

**Comment by davjhan** [comment]
Sorry @twuky, to clarify, I wasn't able to get it working using `bun`, but I was able to get it working using `npm`.
